spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_dev
    username: library_user
    password: libpass
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    default-schema: public
